@DientesLimpios.API_HostAddress = https://localhost:7149/api/consultorios

GET {{DientesLimpios.API_HostAddress}}/019DBD19-4253-7561-B468-62CF3282CB53
Accept: application/json
Authorization: Bearer CfDJ8McZU5vO9elKhGM_fX8mXY8scBxNUX3GaeCdxvdthPVfB_gEUSEdWhRMNtwxqiRzR4_PAIgwxJp7J9vzBBtNIfAhEw3bWMwICvq7P1FpuODzUxb9nh8Rzw550ResELKhAryH_cbQNapnXOWmvisjq2sibAVHkrA4fWFIwvNemPt1pa9fx4wM2CzG1Qnp3e60HwupoR9IjTld3_DQC6Yne25x1rf0MwGJ0XmjRwzjspSd-qSkwtv55qL7QUNO0Z9uOCCmbFp20k-_1YwD1qlnQVdKUycyfMTy-z5rNGWjAM2LFch8B-swgsR-M4CRv2t-guN_0jkvzxRsQs39Zk2VC3E7Hkygo2HVIXzw5UmorTsL-1WoG2NHeJGuFZS0F4dieOMtxwJEWEXBgjBDVmEpIO4zWfeY8I-Llghy9yqlrSSN98SYJEiMrF3YIDE2Rw4GL09cZFzmsOmEx1YbxImtHWhrJkFY9_U55CjvKdFUsC1Tzuo4qiBs6CG7_lH2L9tI-fN1iQzYLmB2ERx3_fwoARo08lzF8guCNxqdYqlKji38-Yff18w_hf4HSnlrIJ_FSbNbPfSaL1uSO5z6eqS1VNpUwXY93SuIodlLeCocNlCIdYoPT1g-Gxvm111DmuDvAC-AznfQe_RfA0i2d9_7-A-D2lH5oN6CovhnSGjoWEpsdu0quowNsdbLbf1VINOIZtAXL4tVHPcbM4PCq69ayhn6SvAdqY0E8sfZx19fRX5P

###

GET {{DientesLimpios.API_HostAddress}}
Accept: application/json
Authorization: Bearer CfDJ8McZU5vO9elKhGM_fX8mXY8scBxNUX3GaeCdxvdthPVfB_gEUSEdWhRMNtwxqiRzR4_PAIgwxJp7J9vzBBtNIfAhEw3bWMwICvq7P1FpuODzUxb9nh8Rzw550ResELKhAryH_cbQNapnXOWmvisjq2sibAVHkrA4fWFIwvNemPt1pa9fx4wM2CzG1Qnp3e60HwupoR9IjTld3_DQC6Yne25x1rf0MwGJ0XmjRwzjspSd-qSkwtv55qL7QUNO0Z9uOCCmbFp20k-_1YwD1qlnQVdKUycyfMTy-z5rNGWjAM2LFch8B-swgsR-M4CRv2t-guN_0jkvzxRsQs39Zk2VC3E7Hkygo2HVIXzw5UmorTsL-1WoG2NHeJGuFZS0F4dieOMtxwJEWEXBgjBDVmEpIO4zWfeY8I-Llghy9yqlrSSN98SYJEiMrF3YIDE2Rw4GL09cZFzmsOmEx1YbxImtHWhrJkFY9_U55CjvKdFUsC1Tzuo4qiBs6CG7_lH2L9tI-fN1iQzYLmB2ERx3_fwoARo08lzF8guCNxqdYqlKji38-Yff18w_hf4HSnlrIJ_FSbNbPfSaL1uSO5z6eqS1VNpUwXY93SuIodlLeCocNlCIdYoPT1g-Gxvm111DmuDvAC-AznfQe_RfA0i2d9_7-A-D2lH5oN6CovhnSGjoWEpsdu0quowNsdbLbf1VINOIZtAXL4tVHPcbM4PCq69ayhn6SvAdqY0E8sfZx19fRX5P

###

POST {{DientesLimpios.API_HostAddress}}
Content-Type: application/json
Authorization: Bearer CfDJ8McZU5vO9elKhGM_fX8mXY8scBxNUX3GaeCdxvdthPVfB_gEUSEdWhRMNtwxqiRzR4_PAIgwxJp7J9vzBBtNIfAhEw3bWMwICvq7P1FpuODzUxb9nh8Rzw550ResELKhAryH_cbQNapnXOWmvisjq2sibAVHkrA4fWFIwvNemPt1pa9fx4wM2CzG1Qnp3e60HwupoR9IjTld3_DQC6Yne25x1rf0MwGJ0XmjRwzjspSd-qSkwtv55qL7QUNO0Z9uOCCmbFp20k-_1YwD1qlnQVdKUycyfMTy-z5rNGWjAM2LFch8B-swgsR-M4CRv2t-guN_0jkvzxRsQs39Zk2VC3E7Hkygo2HVIXzw5UmorTsL-1WoG2NHeJGuFZS0F4dieOMtxwJEWEXBgjBDVmEpIO4zWfeY8I-Llghy9yqlrSSN98SYJEiMrF3YIDE2Rw4GL09cZFzmsOmEx1YbxImtHWhrJkFY9_U55CjvKdFUsC1Tzuo4qiBs6CG7_lH2L9tI-fN1iQzYLmB2ERx3_fwoARo08lzF8guCNxqdYqlKji38-Yff18w_hf4HSnlrIJ_FSbNbPfSaL1uSO5z6eqS1VNpUwXY93SuIodlLeCocNlCIdYoPT1g-Gxvm111DmuDvAC-AznfQe_RfA0i2d9_7-A-D2lH5oN6CovhnSGjoWEpsdu0quowNsdbLbf1VINOIZtAXL4tVHPcbM4PCq69ayhn6SvAdqY0E8sfZx19fRX5P

{
  "nombre": "Consultorio C"
}

###

PUT {{DientesLimpios.API_HostAddress}}/019DDC17-6A0F-7013-8C90-FA39EA01C256
Content-Type: application/json
Authorization: Bearer CfDJ8McZU5vO9elKhGM_fX8mXY8scBxNUX3GaeCdxvdthPVfB_gEUSEdWhRMNtwxqiRzR4_PAIgwxJp7J9vzBBtNIfAhEw3bWMwICvq7P1FpuODzUxb9nh8Rzw550ResELKhAryH_cbQNapnXOWmvisjq2sibAVHkrA4fWFIwvNemPt1pa9fx4wM2CzG1Qnp3e60HwupoR9IjTld3_DQC6Yne25x1rf0MwGJ0XmjRwzjspSd-qSkwtv55qL7QUNO0Z9uOCCmbFp20k-_1YwD1qlnQVdKUycyfMTy-z5rNGWjAM2LFch8B-swgsR-M4CRv2t-guN_0jkvzxRsQs39Zk2VC3E7Hkygo2HVIXzw5UmorTsL-1WoG2NHeJGuFZS0F4dieOMtxwJEWEXBgjBDVmEpIO4zWfeY8I-Llghy9yqlrSSN98SYJEiMrF3YIDE2Rw4GL09cZFzmsOmEx1YbxImtHWhrJkFY9_U55CjvKdFUsC1Tzuo4qiBs6CG7_lH2L9tI-fN1iQzYLmB2ERx3_fwoARo08lzF8guCNxqdYqlKji38-Yff18w_hf4HSnlrIJ_FSbNbPfSaL1uSO5z6eqS1VNpUwXY93SuIodlLeCocNlCIdYoPT1g-Gxvm111DmuDvAC-AznfQe_RfA0i2d9_7-A-D2lH5oN6CovhnSGjoWEpsdu0quowNsdbLbf1VINOIZtAXL4tVHPcbM4PCq69ayhn6SvAdqY0E8sfZx19fRX5P

{
  "nombre": "Consultorio C - Actualizado"
}

###

DELETE {{DientesLimpios.API_HostAddress}}/019dbffa-4dab-7919-a50f-f8fc614796a0
Accept: application/json
