@DientesLimpios.API_HostAddress = http://localhost:5112/api/dentistas

GET {{DientesLimpios.API_HostAddress}}/019dcfa8-b84f-74c9-b47f-ef6786b3759f
Accept: application/json

###

GET {{DientesLimpios.API_HostAddress}}?pagina=1&registrosPorPagina=10
Accept: application/json

###

POST {{DientesLimpios.API_HostAddress}}
Content-Type: application/json

{
  "nombre": "Dentista C",
  "email": "dentistaC@ejemplo.com"
}

###

PUT {{DientesLimpios.API_HostAddress}}/019dcfa8-b84f-74c9-b47f-ef6786b3759f
Content-Type: application/json

{
  "nombre": "Dentista B - Actualizado",
  "email": "dentistaBActualizado@ejemplo.com"
}

###

DELETE {{DientesLimpios.API_HostAddress}}/019dcfa9-de57-7db5-9633-2d3230936543
Accept: application/json
